### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function A3Rev\WCPSAD\order_by_onsale_post_clauses() 

### ISSUE THREAD

**Issue by k-m-engin** [a3rev/woocommerce-product-sort-and-display#2]
On Woocommerce 3.6.5 using "Sort By On Sale" in Internet Explorer I am getting the following error:
_Fatal error: Uncaught Error: Call to undefined function A3Rev\WCPSAD\order_by_onsale_post_clauses() in /www/wp-content/plugins/woocommerce-product-sort-and-display/classes/class-wc-psad-functions.php:111 Stack trace: #0 /www/wp-includes/class-wp-hook.php(289): A3Rev\WCPSAD\Functions::change_orderby_query(Array) #1 /www/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 /www/wp-content/plugins/woocommerce/includes/class-wc-query.php(500): apply_filters('woocommerce_get...', Array, 'onsale', '') #3 /www/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php(64): WC_Query->get_catalog_ordering_args() #4 /www/wp-content/plugins/elementor-pro/modules/woocommerce/classes/products-renderer.php(24): ElementorPro\Modules\Woocommerce\Classes\Products_Renderer->parse_query_args() #5 /www/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/products.php(214): ElementorPro\Modules\Woocommerce\Classes\Products_Renderer->__construct(Array, 'products') #6 /www/wp-content/plugins/eleme in /www/wp-content/plugins/woocommerce-product-sort-and-display/classes/class-wc-psad-functions.php on line 111 _

WCPSAD Version: 2.0.1

Recommend changing class-wc-psad-functions.php line 111 to: 
`$ordering_args = self::order_by_onsale_post_clauses( $ordering_args );`

**Comment by alextuan** [comment]
Yes, just check and it has that issue when you are using WC with version lower 3.8 , we will fix but you should update to latest version of WC so it will solve the issue you see
